# Generated by Django 4.0.3 on 2022-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JulaneHotel', '0003_admin_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='dateofuse',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
