# Generated by Django 4.0.3 on 2022-03-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JulaneHotel', '0006_rooms_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='dateofuse',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='roomtype',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='roomID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JulaneHotel.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
